### ISSUE TITLE
split panel eklenmesi.

### ISSUE THREAD

**Issue by osbm** [bauaai/streamlit-app#17]

**Comment by osbm** [comment]
Split panel hakkında [discussion](https://github.com/giswqs/leafmap/discussions/233#discussioncomment-2529797)

**Comment by osbm** [comment]
see: [A notebook about tiles at folium](https://colab.research.google.com/github/google/earthengine-community/blob/master/tutorials/detecting-changes-in-sentinel-1-imagery-pt-2/index.ipynb#scrollTo=VIiyf6azf4mU)

**Comment by EFCK** [comment]
https://leafmap.org/notebooks/12_split_map/ sayfasındaki leafmap.split_map() metodu kullanarak split panel üretmemiz mümkün.
Bu metot sol ve sağ layerları parametre olarak alıyor yani bizim layerları haritaya eklemeden üretip depolamamız lazım.
Bunun için https://leafmap.org/common/?h=get_local#leafmap.common.get_local_tile_layer metodu önerilmiş ama bu parametre olarak string türünden source istiyor. Layerları haritaya eklemeden depolamayı bulmamız lazım.
![hata](https://user-images.githubusercontent.com/81926833/162823415-b312405b-3f78-4610-a7e8-4df7ae87719c.png)
![source](https://user-images.githubusercontent.com/81926833/162823491-d6b05d52-ef36-408f-9186-50716b7e4354.png)
.
