### ISSUE TITLE
çıktıyı uygulamalara aktarma

### ISSUE THREAD

**Issue by EFCK** [bauaai/streamlit-app#42]
Streamlit uygulamamız üzerindeki hesaplanan veriler (inputlar, outputlar dahil) dış uygulamalara aktarılabilmektedir (örn: JSON, GeoJSON vb.).

**Comment by osbm** [comment]
Bunu nasıl yapıcağımız hakkında plan yapmamız lazım

**Comment by osbm** [comment]
Timelapse ve Yangın Analizi sayfaları çıktısını gif mp4 png gibi formatlarda verebilmek lazım
